services:
  mirage:
    build: .
    container_name: mirage_app
    volumes:
      - ./src:/app/src
      - ./docs:/app/docs
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true

